import * as Schema from "effect/Schema";
import * as Effect from "effect/Effect";

import {
  EnvironmentId,
  EventId,
  IsoDateTime,
  ThreadId,
  TrimmedNonEmptyString,
} from "./baseSchemas.ts";

/** A privacy-safe, transport-neutral notification emitted by orchestration. */
export const AgentNotificationKind = Schema.Literals([
  "agent_completed",
  "plan_ready",
  "input_required",
  "agent_failed",
]);
export type AgentNotificationKind = typeof AgentNotificationKind.Type;

export const AgentNotificationInputKind = Schema.Literals(["approval", "input"]);
export type AgentNotificationInputKind = typeof AgentNotificationInputKind.Type;

export const AGENT_NOTIFICATION_MAX_TITLE_LENGTH = 120;
const AgentNotificationTitle = TrimmedNonEmptyString.check(
  Schema.isMaxLength(AGENT_NOTIFICATION_MAX_TITLE_LENGTH),
);

/**
 * A notification route is deliberately relative. Each channel is responsible
 * for resolving it against its own trusted origin/window.
 */
export const AgentNotificationDeepLink = Schema.String.check(
  // Only accept a relative, two-segment thread route. Percent escapes are
  // validated here and encoded path separators are rejected so a renderer
  // cannot smuggle an arbitrary route through notification click handling.
  Schema.isPattern(
    /^\/threads\/(?![^/]*%(?:2[fF]|5[cC]))(?:[^/?#%]|%[\dA-Fa-f]{2})+\/(?![^/]*%(?:2[fF]|5[cC]))(?:[^/?#%]|%[\dA-Fa-f]{2})+$/u,
  ),
);
export type AgentNotificationDeepLink = typeof AgentNotificationDeepLink.Type;

export const AgentNotificationEvent = Schema.Struct({
  eventId: EventId,
  environmentId: EnvironmentId,
  threadId: ThreadId,
  kind: AgentNotificationKind,
  completionId: Schema.optional(TrimmedNonEmptyString),
  failureId: Schema.optional(TrimmedNonEmptyString),
  requestId: Schema.optional(TrimmedNonEmptyString),
  inputKind: Schema.optional(AgentNotificationInputKind),
  planId: Schema.optional(TrimmedNonEmptyString),
  planUpdatedAt: Schema.optional(IsoDateTime),
  projectTitle: Schema.optional(AgentNotificationTitle),
  threadTitle: Schema.optional(AgentNotificationTitle),
  occurredAt: IsoDateTime,
  deepLink: AgentNotificationDeepLink,
});
export type AgentNotificationEvent = typeof AgentNotificationEvent.Type;

/**
 * The selectable sound set. `original-*` are the CC0 samples this app shipped
 * before sounds were selectable (see THIRD_PARTY_NOTICES.md); the rest are
 * generated by `pnpm sounds:generate`.
 */
export const AgentNotificationSoundId = Schema.Literals([
  "none",
  "chime-soft",
  "marimba",
  "ping",
  "bloom",
  "pluck",
  "knock",
  "descend",
  "alert",
  "original-chimes",
  "original-ding",
  "original-alarm",
  "original-negative",
]);
export type AgentNotificationSoundId = typeof AgentNotificationSoundId.Type;

/** Picker order. Quiet-and-short first, the pre-existing samples last. */
export const AGENT_NOTIFICATION_SOUND_IDS: readonly AgentNotificationSoundId[] = [
  "chime-soft",
  "marimba",
  "ping",
  "bloom",
  "pluck",
  "knock",
  "descend",
  "alert",
  "original-chimes",
  "original-ding",
  "original-alarm",
  "original-negative",
  "none",
];

/** Which sound each notification kind plays. Every kind is independent. */
export const AgentNotificationSounds = Schema.Struct({
  agent_completed: AgentNotificationSoundId,
  plan_ready: AgentNotificationSoundId,
  input_required: AgentNotificationSoundId,
  agent_failed: AgentNotificationSoundId,
});
export type AgentNotificationSounds = typeof AgentNotificationSounds.Type;

/**
 * Completion defaults to the short generated chime rather than the original
 * two-second sample, which was long enough to be intrusive for the event that
 * fires most often. The other kinds keep the sample they have always used.
 */
export const DEFAULT_AGENT_NOTIFICATION_SOUNDS: AgentNotificationSounds = {
  agent_completed: "chime-soft",
  plan_ready: "original-ding",
  input_required: "original-alarm",
  agent_failed: "original-negative",
};

export const AgentNotificationPreferences = Schema.Struct({
  enabled: Schema.Boolean,
  notifyOnCompletion: Schema.Boolean,
  notifyOnPlanReady: Schema.Boolean,
  notifyOnInput: Schema.Boolean,
  notifyOnFailure: Schema.Boolean,
  playSound: Schema.Boolean.pipe(Schema.withDecodingDefault(Effect.succeed(true))),
  sounds: AgentNotificationSounds.pipe(
    Schema.withDecodingDefault(Effect.succeed(DEFAULT_AGENT_NOTIFICATION_SOUNDS)),
  ),
  showProjectAndThreadNames: Schema.Boolean,
});
export type AgentNotificationPreferences = typeof AgentNotificationPreferences.Type;

export const DesktopNotificationAttempt = Schema.Literals([
  "attempted",
  "disabled",
  "suppressed-focused",
  "unsupported",
  "error",
]);
export type DesktopNotificationAttempt = typeof DesktopNotificationAttempt.Type;

export const DEFAULT_AGENT_NOTIFICATION_PREFERENCES: AgentNotificationPreferences = {
  enabled: false,
  notifyOnCompletion: true,
  notifyOnPlanReady: true,
  notifyOnInput: true,
  notifyOnFailure: true,
  playSound: true,
  sounds: DEFAULT_AGENT_NOTIFICATION_SOUNDS,
  showProjectAndThreadNames: true,
};

export function isAgentNotificationEnabled(
  preferences: AgentNotificationPreferences,
  kind: AgentNotificationKind,
): boolean {
  if (!preferences.enabled) return false;
  switch (kind) {
    case "agent_completed":
      return preferences.notifyOnCompletion;
    case "plan_ready":
      return preferences.notifyOnPlanReady;
    case "input_required":
      return preferences.notifyOnInput;
    case "agent_failed":
      return preferences.notifyOnFailure;
  }
}
